---
# file: roles/storage/lvm/tasks/install.yml
# These tasks are run on all nodes

- name: Ensure required packages are installed
  apt: pkg={{ item }} state=latest cache_valid_time=86400 update_cache=yes
  with_items:
   - lvm2
   - parted
   - xfsprogs

- name: Install encryption
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - ecryptfs-utils
    - xfsprogs

- name: Storage | Unmount the temporary drive first
  sudo: true
  shell: umount /mnt
  ignore_errors: yes
  when: azure

- name: Storage | Wipe them out. All of them.
  sudo: true
  shell: dd if=/dev/zero of=/dev/sdb bs=512 count=1
  ignore_errors: yes
  when: azure

- name: Storage | Remove existing temporary drive (Azure)
  sudo: true
  shell: parted --script /dev/sdb rm 1
  ignore_errors: yes
  when: azure

- name: Storage | Unmount the temporary drive first. Mystery, needs to be done twice on G5 instance
  sudo: true
  shell: umount /mnt
  ignore_errors: yes
  when: azure

- name: Storage | Wipe them out. All of them. Mystery, needs to be done twice on G5 instance
  sudo: true
  shell: dd if=/dev/zero of=/dev/sdb bs=512 count=1
  ignore_errors: yes
  when: azure

- name: Storage | Remove existing temporary drive (Azure). Mystery, needs to be done twice on G5 instance
  sudo: true
  shell: parted --script /dev/sdb rm 1
  ignore_errors: yes
  when: azure


- name: Storage | Create a volume group white listed devices
  lvg: vg=volume_group pvs={{ lvm_device_whitelist }} state=present 
  register: lvm_volume_created

- name: Storage | Create logical volume
  lvol: vg=volume_group lv=logical_volume state=present  size=100%FREE

- name: Storage | Create file system
  filesystem: dev=/dev/volume_group/logical_volume  fstype={{ brick_file_system }}
