---
#consonance_arch_version: 1.1-alpha.5
#queueName: pancancer_arch_3
#queueHost: "{{ lookup('env','PUBLIC_IP_ADDRESS') }}"
hostUser: ubuntu
seqware_engine: whitestar
dcc_storage_version: 0.0.48
dcc_target: collab
