---
- name: Get Architecture3 jar file
  get_url: url=https://seqwaremaven.oicr.on.ca/artifactory/simple/seqware-release/io/consonance/consonance-arch/{{ consonance_arch_version }}/consonance-arch-{{ consonance_arch_version }}.jar dest=/home/ubuntu/consonance-arch-{{ consonance_arch_version }}.jar

# TODO: above is where I would replace the consonance jar with a custom version if I modify the worker (which I will have to)
# TODO: install Dockstore CLI and jar

# The "endless" flag for the worker is not a true/false, it's "--endless" or "".
- name: Conditionally turn endless_worker_flag on
  set_fact: endless_worker_flag=" --endless "
  when: endless_worker is defined and endless_worker

- name: Conditionally turn endless_worker_flag off
  set_fact: endless_worker_flag=""
  when: endless_worker is not defined or not endless_worker

- name: Get kill-worker script
  template: src=kill_worker_daemon.j2 dest=/home/ubuntu/kill_worker_daemon.sh

- name: Get run-worker script
  template: src=run_worker_daemon.j2 dest=/home/ubuntu/run_worker_daemon.sh

- name: queueHost is
  debug: var={{ queueHost }}

- name: Template workerConfig
  template: src=workerConfig.j2 dest=/home/ubuntu/workerConfig.ini owner=ubuntu

- name: Create .seqware directory
  file: path=/home/ubuntu/.seqware state=directory owner=ubuntu
  when: seqware_use_custom_settings is defined and seqware_use_custom_settings

- name: Copy base custom seqware settings
  copy: src=../files/seqware_settings.ini dest=/home/ubuntu/.seqware/settings owner=ubuntu
  when: seqware_use_custom_settings is defined and seqware_use_custom_settings

#- name: Uncomment the custom seqware settings, IF you've requested that.
#  replace: dest=/home/ubuntu/workerConfig.ini regexp='^(\#seqware-)(.*)$' replace='seqware-\2' backup=yes owner=ubuntu
#  when: seqware_use_custom_settings is defined and seqware_use_custom_settings

- name: Copy over keys/credentials for workers.
  copy: src={{ item }} dest={{ item }} owner=ubuntu
  with_fileglob:
    - /home/ubuntu/.gnos/*
    - /home/ubuntu/.aws/*

- name: Install avro
  pip: name=avro version=1.7.7 executable=pip2.7

- name: Install schema-salad
  pip: name=schema-salad version=1.7.20160316150109 executable=pip2.7

- name: Install cwltool
  pip: name=cwltool version=1.0.20160316150250 executable=pip2.7

- name: Install cwl-runner
  pip: name=cwl-runner executable=pip2.7

# install dcc-storage

- name: Create required directory
  sudo: true
  file: path=/icgc/dcc-storage/ owner=ubuntu state=directory

- name: Create working directory
  sudo: true
  file: path=/icgc/dcc-storage/archive owner=ubuntu state=directory

- name: Get file
  get_url: url=https://seqwaremaven.oicr.on.ca/artifactory/dcc-release/org/icgc/dcc/dcc-storage-client/{{ dcc_storage_version }}/dcc-storage-client-{{ dcc_storage_version }}-dist.tar.gz dest=/icgc/dcc-storage/archive

- name: Unarchive the dcc tool
  unarchive: src=/icgc/dcc-storage/archive/dcc-storage-client-{{ dcc_storage_version }}-dist.tar.gz dest=/icgc/dcc-storage/archive  copy=no

- name: Copy files extracted files into correct location
  shell: creates=/icgc/dcc-storage/bin/dcc-storage-client mv /icgc/dcc-storage/archive/dcc-storage-client-{{ dcc_storage_version }}/* /icgc/dcc-storage/

- name: Template shell script
  template: src=dcc-storage-client.j2 dest=/icgc/dcc-storage/bin/dcc-storage-client owner=ubuntu

# end dcc-storage

- name: Run worker as daemon
  sudo: true
  shell: chdir=/home/ubuntu nohup bash /home/ubuntu/run_worker_daemon.sh &
